### PR TITLE
feat: add `Link` property to supported table columns

### LINKED ISSUE #36: Add link to the the issue's `html_url` in the Notion table
<sub>[Discuss in #**issue-36--add-link-to-the-the-issues-html_url-in-the-notion-table**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C02HQRCSV32)</sub>

**Is your feature request related to a problem? Please describe.**
It would be nice to have a direct link to the issue from within Notion to make it easier to jump between the two tools.

**Describe the solution you'd like**
Add a `URL` field in the Notion table and sync the issue's `html_url` to that field.

### PR DESCRIPTION
**Pull request by EndBug**
This PR adds support for a new URL property of the table, which should contain the `html_url`s of the issues. I've currently named the property "Link", but that can of course be changed.

I've also added a `CustomValueMap` interface that can be used instead of `InputPropertyValueMap` so that it forces every input map to have all the properties the action currently supports.

In order for this to work the Notion template should be updated to reflect the change, by adding a new column with the same name as the one used here.

This change still needs to be tested: what's your workflow for testing a change on a branch? I've seen that the CI is updating the build only on the `master` branch, but can I update it manually on this one just to test it?

If so I'll test it directly on this branch before merging 👍🏻 

Fixes #36

### CODE REVIEW

**Review by marissamarym — COMMENTED** [review]
Nice! To answer your questions in the PR description, yes let's change CI to all branches. I didn't realize we didn't have tests set up yet for this action, because we do for the other ones (ex. https://github.com/instantish/memorable-milestones/blob/master/__tests__/main.test.ts). wdyt about adding a quick test to this PR?

**Comment by EndBug** [comment]
Adding tests would definitely be awesome, I'm just wondering if maybe it's better to do this in a dedicated PR...
Anyway, as you prefer, the result, in the end, is the same 😄

**Comment by marissamarym** [comment]
> Adding tests would definitely be awesome, I'm just wondering if maybe it's better to do this in a dedicated PR... Anyway, as you prefer, the result, in the end, is the same 😄

sure, a separate PR works for me!

**Review by marissamarym — APPROVED** [review]
Just one more thing: want to change the template in the README to this link (https://www.notion.so/tryfabric/067329ee12044ec49b7db6b39b26920a?v=38dd7e968874436c810a5e604d2cf12c) as part of this PR? Then it's good to go! 🎉

**Comment by EndBug** [comment]
Well, since it seems it has already been updated, I'm going to merge the PR 👍🏻

**Pull request merged**
